#!/usr/bin/env bash

# CircleCI's conditional workflows will trigger according to whether a test
# is passing of failing. Here we ensure the test returns 0 if Action Models
# is present, and pass `on_success` to the `when` conditional in the config file:
# https://circleci.com/docs/configuration-reference/#the-when-attribute

ACTION_MODELS_PRESENCE=$(git grep bullet_train-action_models Gemfile.lock)

if [[ $ACTION_MODELS_PRESENCE ]]; then
  exit 0
else
  exit 1
fi
