#!/usr/bin/env bash

# https://gist.github.com/vncsna/64825d5609c146e80de8b1fd623011ca
set -euxo pipefail

bundle exec rails db:migrate
GIT_STATUS=`git status db/schema.rb`
echo $GIT_STATUS

if [[ $GIT_STATUS =~ "nothing to commit, working tree clean" ]]; then
  exit 0
else
  # This invocation ensures that our arrays split at new lines, and not BOTH new lines AND spaces.
  # https://unix.stackexchange.com/questions/39473/command-substitution-splitting-on-newline-but-not-space
  set -f
  IFS='
'

  DIFF=`git diff db/schema.rb`
  readarray -t DIFF_LINES <<<"$DIFF"
  for line in "${DIFF_LINES[@]}" ; do
    if [[ $line =~ ^\+ ]] ; then
      if [[ $line =~ ^\+{3} ]] ; then
        # +++ designates a file name, so we skip it.
        echo ""
      else
        ADDITIONS+=($line)
      fi
    fi
  done

  # Reset the settings we edited above.
  unset IFS
  set +f

  if [[ ${#ADDITIONS[@]} == 1 && ${ADDITIONS[0]} =~ ^\+ActiveRecord ]] ; then
    echo "Rails version was updated, but there were no changes to any tables."
    exit 0
  fi

  echo ""
  echo "rails db:migrate made a change to your database's schema."
  echo "Please make sure your database is updated locally before pushing to CircleCI:"
  git diff db/schema.rb
  exit 1
fi
