#!/usr/bin/env bash

bundle exec rails db:migrate
GIT_STATUS=`git status db/schema.rb`
if [[ $GIT_STATUS =~ "nothing to commit, working tree clean" ]]; then
  exit 0
else
  echo $GIT_STATUS
  exit 1
fi
