# Be sure to restart your server when you modify this file.

# Add new inflection rules using the following format. Inflections
# are locale specific, and you may define rules for as many different
# locales as you wish. All of these examples are active by default:
# ActiveSupport::Inflector.inflections(:en) do |inflect|
#   inflect.plural /^(ox)$/i, "\\1en"
#   inflect.singular /^(ox)en/i, "\\1"
#   inflect.irregular "person", "people"
#   inflect.uncountable %w( fish sheep )
# end

# These inflection rules are supported but not enabled by default:
# ActiveSupport::Inflector.inflections(:en) do |inflect|
#   inflect.acronym "RESTful"
# end

ActiveSupport::Inflector.inflections(:en) do |inflect|
  # 🚫 DEFAULT BULLET TRAIN INFLECTIONS
  # Typically you should avoid adding your own functionality in this section to avoid merge conflicts in the future.

  # TODO Move this into the `bullet_train` package.
  # "_by" is a particularly common suffix for associations in Bullet Train applications (e.g. `created_by`, etc.)
  # but it gets pluralized incorrectly as "_bies". This should fix both Super Scaffolding for those fields and
  # the resulting invocations of the scope validator that are generated by Super Scaffolding.
  inflect.irregular "by", "bys"

  # ✅ YOUR APPLICATION'S INFLECTIONS
  # You can add your own custom inflections below.
end
