json.extract! membership,
  :id,
  :user_id,
  :team_id,
  :invitation_id,
  :user_first_name,
  :user_last_name,
  :user_profile_photo_id,
  :user_email,
  :added_by_id,
  :platform_agent_of_id,
  :role_ids,
  :platform_agent,
  # 🚅 super scaffolding will insert new fields above this line.
  :created_at,
  :updated_at
