:concurrency: 5
staging:
  :concurrency: 5
production:
  :concurrency: 5
:queues:
  - critical
  - default
  - mailers
  - low
  - action_mailbox_routing
:scheduler:
  webhooks_endpoints_deactivation:
    enabled: true
    interval:
      - 6h
      - first_in: 5m
    class: Webhooks::Outgoing::EndpointsDeactivationJob
