#!/usr/bin/env bash

# https://gist.github.com/vncsna/64825d5609c146e80de8b1fd623011ca
# Note we're not using `x` because it's noisy. If you want to use it for debugging, uncomment the line below.
set -euo pipefail
#set -x
#
export SPRING=true

rake db:migrate VERSION=`ls db/migrate | sort | tail -n 4 | head -n 1`
git checkout app config db test
git clean -d -f app config db test
