name: "Dynamic Matrix"
on:
  workflow_call:
    inputs:
      numberOfTestNodes:
        description: 'Number of test nodes (4 if blank)'
        required: false
        type: number
      testRunnersPerNode:
        description: 'Test runners per node (if blank 4 for public repos, 2 for private repos)'
        required: false
        type: number
    outputs:
      matrix:
        description: The matrix
        value: ${{ jobs.calculate_matrix.outputs.matrix }}
      total_runners:
        description: The total number of runners
        value: ${{ jobs.calculate_matrix.outputs.total_runners }}

jobs:
  example_job:
    name: Generate output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      matrix: ${{ steps.calculate_matrix.outputs.result }}
      total_runners: ${{ steps.calculate_total_runners.outputs.result }}
    steps:
      - uses: actions/github-script@v7
        id: calculate_total_runners
        name: Calculate Total Runners
        env:
          REPO_VISIBILITY: ${{ github.event.repository.visibility }}
          NUMBER_OF_TEST_NODES: ${{ inputs.numberOfTestNodes }}
          TEST_RUNNERS_PER_NODE: ${{ inputs.testRunnersPerNode }}
        with:
          script: |
            var numberOfTestNodes = process.env.NUMBER_OF_TEST_NODES || 4
            var testRunnersPerNode = process.env.TEST_RUNNERS_PER_NODE
            if(!testRunnersPerNode){
              if(process.env.REPO_VISIBILITY == "public"){
                testRunnersPerNode = 4
              }else{
                testRunnersPerNode = 2
              }
            }
            console.log("total runners =====")
            console.log(testRunnersPerNode * numberOfTestNodes)
            return testRunnersPerNode * numberOfTestNodes

      - uses: actions/github-script@v7
        id: calculate_matrix
        name: Calculate Matrix
        env:
          REPO_VISIBILITY: ${{ github.event.repository.visibility }}
          NUMBER_OF_TEST_NODES: ${{ inputs.numberOfTestNodes }}
          TEST_RUNNERS_PER_NODE: ${{ inputs.testRunnersPerNode }}
        with:
          script: |
            var numberOfTestNodes = process.env.NUMBER_OF_TEST_NODES || 4
            var testRunnersPerNode = process.env.TEST_RUNNERS_PER_NODE
            if(!testRunnersPerNode){
              if(process.env.REPO_VISIBILITY == "public"){
                testRunnersPerNode = 4
              }else{
                testRunnersPerNode = 2
              }
            }
            try {
              var matrix = []
              for(var i = 1; i <= numberOfTestNodes; i++){
                var runners = []
                for(var j = 1; j <= testRunnersPerNode; j++){
                  runners.push( (i - 1) * testRunnersPerNode + j );
                }
                matrix.push(runners.join(`,`))
              }
              console.log("matrix ====")
              console.log(matrix)
              return matrix
            } catch(err) {
              core.summary.addRaw("Error while calculating matrix", true)
              core.summary.addRaw(err.toString(), true)
              core.error("Error while calculating matrix")
              core.setFailed(err)
            }
