# This workflow will run whenever a PR is opened or changed.
#
# It will run tests and a few safety checks.
#
# If everything passes it can be set to auto-deploy to your staging app on Heroku.
#
# This workflow is primarily meant to be triggered automatically, but it can be run manually.
name: " 💻 PR CI (staging)"
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  calculate_matrix:
    name: 🧮 Calculate Dynamic Matrix
    #uses: ./.github/workflows/_dynamic_matrix.yml
    uses: bullet-train-co/parallel-test-dynamic-matrix/action.yml@main
    secrets: inherit
  check_calculations:
    runs-on: ubuntu-latest
    name: Check Calculation Output
    needs: [calculate_matrix]
    steps:
      - name: Show output
        run: echo "${{ needs.calculate_matrix.outputs.matrix }}"
        shell: bash
      - name: Show output
        run: echo "${{ needs.calculate_matrix.outputs.total_runners }}"
        shell: bash
  minitest:
    name: 🧪 Minitest
    uses: ./.github/workflows/_run_tests.yml
    secrets: inherit
    needs: [calculate_matrix]
  standardrb:
    name: 🔬 Standardrb
    uses: ./.github/workflows/_standardrb.yml
    secrets: inherit
  db_schema:
    name: 🔎 DB Schema
    uses: ./.github/workflows/_database_schema_check.yml
    secrets: inherit
  combine_runtime_logs:
    name: 🪵 Combine Runtime Logs
    uses: ./.github/workflows/_combine_runtime_logs.yml
    secrets: inherit
    needs: [minitest]
  combine_coverage_data:
    name: 🫣 SimpleCov
    uses: ./.github/workflows/_combine_coverage_data.yml
    secrets: inherit
    needs: [minitest]
  combine_summary_logs:
    name: 📊 Test Results
    uses: ./.github/workflows/_combine_summary_logs.yml
    secrets: inherit
    needs: [minitest]
    if: ${{ always() }}
  # If you'd like to auto-deploy to your staging environment you can uncomment this next block.
  # You'll need to set HEROKU_EMAIL and HEROKU_API_KEY in your repo secrets.
  # Be sure to set the app name correctly below.
  # deploy:
  #   name: 🚢 Deploy to Heroku
  #   uses: ./.github/workflows/_deploy_heroku.yml
  #   needs: [minitest, standardrb, db_schema]
  #   secrets: inherit
  #   with:
  #     heroku-app-name: ""
